config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  devise_for :users
  root to: 'pages#home'
  resources :cars do
    resources :bookings, only: [ :new, :create, :show]
  end
  resources :bookings, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'profile', to: 'pages#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/car.rb
class Car < ApplicationRecord
  include PgSearch::Model

  has_many :bookings, dependent: :destroy
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many_attached :photos


  # has_many_attached :photos
  pg_search_scope :search_by_brand_and_description,
    against: [ :brand, :description ],
    using: {
      tsearch: { prefix: true }
    }

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :destroy]

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
    authorize @booking
  end

  def show

  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car_id = params[:car_id]
    @booking.user_id = current_user.id
    authorize @booking
    if @booking.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to cars_path
  end

  private

  # def set_car
  #   @car = Car.find(params[:car_id])
  #   authorize @car
  # end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action :set_car, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @cars = policy_scope(Car).search_by_brand_and_description(params[:query])
      @markers = @cars.geocoded.map do |car|
        {
          lat: car.latitude,
          lng: car.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { car: car }),
          image_url: helpers.asset_url('car.svg')
        }
      end
    else
      @cars = policy_scope(Car).all
      @markers = @cars.geocoded.map do |car|
        {
          lat: car.latitude,
          lng: car.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { car: car }),
          image_url: helpers.asset_url('car.svg')
        }
      end
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    authorize @car
    # @car.user = current_user
    @car.user_id = current_user.id
    if @car.save
      redirect_to car_path(@car)
    else
      raise
      render :new
    end
  end

  def edit
  end

  def update
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car.destroy
    redirect_to profile_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:brand, :description, :price, :address, photos: []) #photo upload need to install cloudinary
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

  def profile
    @bookings = current_user.bookings
    @cars = current_user.cars
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class='container mt-5'>
  <div class="form">
    <h1>Reserve</h1>
    <%= simple_form_for [@car, @booking] do |f| %>
      <%= f.input :start_time, as: :string, input_html: {class: "datepicker"} %>
      <%= f.input :end_time, as: :string, input_html: {class: "datepicker"} %>
      <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class='container text-center mt-4'>
  <h1>Your car has been booked. Enjoy the ride</h1>
  <%= link_to "Home page", root_path, class: "btn btn-primary mt-3" %>
</div>

app/views/cars/_info_window.html.erb
<h2><%= car.brand %></h2>
<p><%= car.address %></p>

app/views/cars/edit.html.erb
<h1 class='text-center mt-3 mb-5' style='color: black;'>Edit a car</h1>
<div class="form-new">
  <%= simple_form_for @car do |f| %>
    <%= f.input :brand %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cars/index.html.erb
<div class="banner-index" style="background-image: url(https://images.unsplash.com/photo-1506469717960-433cebe3f181?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80);">
  <h1 class='text-center'>Book the best car for your week-end at milan</h1>
  <div class ="banner-content-index">
    <form>
      <%= form_tag cars_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "searchbar-index",
          placeholder: "Find a car"
        %>
        <%= submit_tag "Search", class: "search-btn" %>
      <% end %>
    </form>
  </div>
</div>

<div class='flex_div'>
  <div>
    <div class='cards mr-3'>
      <% @cars.each do |car|%>
        <div class="card-trip">
          <% if car.photos.attached? %>
            <%= cl_image_tag car.photos.first.key%>
          <% end  %>
          <div class="card-trip-infos">
            <div>
              <h2><%= link_to car.brand, car_path(car.id) %></h2>
              <p><%= car.description %></p>
              <p><%= car.address %></p>
            </div>
            <h2 class="card-trip-pricing"><%= car.price %> $</h2>
          </div>
      </div>
      <% end  %>
  </div>
  </div>
<div id="map"
   style="width: 55%; height: auto;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</div>

app/views/cars/new.html.erb
<h1 class='text-center mb-3 mt-5' style='color: black;'>Add new car</h1>
<div class="form-new">
  <%= simple_form_for @car do |f| %>
    <%= f.input :brand %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="container mt-4 mb-4" style="background-color: rgb(240,240,240);">
  <div class="show-image-container w-100">
    <div id="carouselExampleControls" class="carousel slide w-100" data-ride="carousel">

      <div class="carousel-inner w-100">
        <% @car.photos.each.with_index do |photo, index| %>
          <div class="carousel-item <%= index == 0 ? "active" : " " %>">
            <%= cl_image_tag photo.key, class: "d-block carousel-img" %>
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon btn-red" aria-hidden="true"></span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon btn-red" aria-hidden="true"></span>
      </a>
    </div>
  </div>
  <div class="show-container">

      <div class="sub-container">
        <div class="brand">
          <h3> <%= @car.brand %> </h3>
          <p class='pb-3'>  <%= @car.description %> </p>
        </div>

        <div class="show-description">
          <p> <%= image_tag 'parking.webp', class:"icons mr-3 ml-5" %> Free parking in city center </p>
          <p> <%= image_tag 'petrol.webp', class:"icons mr-3 ml-5" %> Refurbish at gas stantion </p>
          <p> <%= image_tag 'sensors.webp', class:"icons mr-3 ml-5" %> Parking alerts with sensors </p>
          <p> <%= image_tag 'smoking.webp', class:"icons mr-3 ml-5" %> No smoking in the car </p>

        </div>
      </div>
      <div class="sub-container-2">
        <div class="star-flex">
          <p> <strong><%= @car.price %> € / day </strong> </p>
        </div>
          <div class="container-dates">
            <div class='container mt-5'>
              <div class="form">

              <h1 class='mb-3' style="font-family: 'Poppins', sans-serif; font-weight: 700; color: rgb(220,100,100);">Reserve</h1>

                <%= simple_form_for [@car, @booking] do |f| %>
                  <%= f.input :start_time, as: :string, input_html: {class: "datepicker"} %>
                  <%= f.input :end_time, as: :string, input_html: {class: "datepicker"} %>
                  <%= f.submit %>
                <% end %>
              </div>
            </div>
          </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VINTAGERENT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'components/navbar' %>
    <div class="main-container">
      <%= yield %>
    </div>
    <%= render 'components/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class= "home-page">

<div class="banner-content">
  <h1 class='banner_title' id="phrase" class="mt-5">Book your dream car in one click</h1>

  <div class='searchbar mt-4'>
    <%= form_tag cars_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search_bar",
        placeholder: "Find a car"
      %>
      <%= submit_tag "Search", class: "btn search_btn mt-3 ml-2" %>
    <% end %>
</div>

</div>



</div>

app/views/pages/profile.html.erb
<div class="add-car-button">
  <%= link_to new_car_path, class:"btn btn-add-car" do   %>
    <i class="fas fa-car-alt"></i> Add Car
  <% end %>
</div>

<div class="profile-main-container">

    <div>
      <h3>My Profile</h3>

      <div class="profile-container">
        <div class="">
          <img class='avatar-bordered' src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png">
        </div>

        <div class="user-details">
          <p> <i class="fas fa-signature"></i> <%= current_user.name %> </p>
          <p> <i class="fas fa-map-marked"></i> <%= current_user.address %> </p>
          <p> <i class="fas fa-at"></i> <%= current_user.email %> </p>
        </div>

          <div class="my-bookings">
            <h2>My Bookings</h2>
            <% current_user.bookings.each do |booking| %>
             <p> <%= booking.car.brand %> - <%= booking.start_time %> </p>
            <% end %>
          </div>
      </div>

    </div>

        <div class='mr-5'>
        <h3>My Cars</h3>
        <div class="profile-listings">

          <% if @cars.exists? %>
            <% @cars.each do |car|  %>
            <div class="card-trip my_car mt-2 profile-card">
              <% if car.photos.attached? %>
                <%= cl_image_tag car.photos.first.key, class:"car-image" %>
              <% end  %>
              <div class="card-trip-infos profile-car-info">
                <div class="car-info">
                  <h3><%= link_to car.brand, car_path(car.id) %></h3>
                  <p><%= car.description  %></p>
                </div>
              </div>

                <div class="profile-bookings">
                  <ul>
                    <%  car.bookings.each do |booking| %>
                      <li>
                       <p> <i class="far fa-user-circle"></i> <%= booking.user.name %> </p>
                       <p> <i class="far fa-calendar-alt"></i> <%= booking.start_time %> - <%= (booking.end_time - booking.start_time).to_i %> days </p>
                       <!-- <p> <i class="fas fa-euro-sign"></i> <%= booking.total_price %> </p> -->
                       <p> <i class="fas fa-euro-sign"></i> <%= (car.price * (booking.end_time - booking.start_time).to_i).to_i %> </p>
                     </li>
                    <% end %>
                  </ul>
                </div>

                <div class="action">
                  <%= link_to "Edit", edit_car_path(car), class:"btn btn-profile-see"  %>
                  <%= link_to "Delete", car_path(car), method: :delete, remote: true, class:"btn btn-profile-delete"  %>
                </div>

            </div>
            <% end %>
            <% else %>
              <%= link_to "Add a car", new_car_path, class:"btn btn-primary"  %>
          <% end %>
        </div>
      </div>






</div>